server:
  port: 8081

spring:
  application:
    name: auth-service
  main:
    lazy-initialization: true

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres                     # must match docker-compose

  hikari:
    maximum-pool-size: 5
    minimum-idle: 2
    connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        # dialect is auto-detected, no need to specify

  data:
    redis:
      host: localhost
      port: 6379
      password: redis123                    # must match the one in docker-compose

#  # Disable Google OAuth for now (you can enable later)
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ""
#            client-secret: ""

jwt:
  secret: MySuperLongJwtSecretKeyForLocalDevelopmentOnly2026MakeItAtLeast64CharsLong!
  expiry-ms: 86400000          # 24 hours
  refresh-expiry-ms: 604800000 # 7 days

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info