server:
  port: 8083

spring:
  application:
    name: booking-service
  main:
    lazy-initialization: true

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: redis123

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq123

jwt:
  secret: MySuperLongJwtSecretKeyForLocalDevelopmentOnly2026MakeItAtLeast64CharsLong!

booking:
  lock:
    timeout-seconds: 10        # Redisson lock timeout
  grace-period-minutes: 15     # minutes after booking start to auto-cancel if no check-in
  cancellation-window-minutes: 30  # minutes before booking start to allow free cancellation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info