server:
  port: 8082

spring:
  application:
    name: parking-service
  main:
    lazy-initialization: true

  datasource:
    url: jdbc:postgresql://localhost:5432/parking_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: redis123

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq123
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3

jwt:
  secret: MySuperLongJwtSecretKeyForLocalDevelopmentOnly2026MakeItAtLeast64CharsLong!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
