server:
  port: 8086

spring:
  application:
    name: analytics-service
  main:
    lazy-initialization: true

  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq123}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET:MySuperLongJwtSecretKeyForLocalDevelopmentOnly2026MakeItAtLeast64CharsLong!}

services:
  payment-url: ${PAYMENT_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
